"""
Comprehensive domain ontology for Gmail Genie rule classification.

Hostnames are matched via ``hostname_matches_registry`` (exact host or
registered suffix), not naive substring checks on the full From header.
"""

# ---------------------------------------------------------------------------
# Security & identity providers
# ---------------------------------------------------------------------------

SECURITY_DOMAINS = [
    "accounts.google.com",
    "auth0.com",
    "okta.com",
    "duosecurity.com",
    "login.microsoftonline.com",
    "id.apple.com",
    "facebook.com",
    "twitter.com",
    "x.com",
    "gitlab.com",
    "bitbucket.org",
    "dropbox.com",
    "1password.com",
    "lastpass.com",
    "dashlane.com",
    "bitwarden.com",
    "keepersecurity.com",
    "cloudflare.com",
    "authy.com",
    "yubico.com",
]

# ---------------------------------------------------------------------------
# Finance — banks, fintech, payments (US, India, EU)
# ---------------------------------------------------------------------------

FINANCE_DOMAINS = [
    # India — banks
    "hdfcbank.net",
    "hdfcbank.com",
    "icicibank.com",
    "axisbank.com",
    "sbi.co.in",
    "onlinesbi.sbi",
    "kotak.com",
    "kotakbank.com",
    "idfcfirstbank.com",
    "yesbank.in",
    "indusind.com",
    "rblbank.com",
    "federalbank.co.in",
    "bandhanbank.com",
    "pnb.co.in",
    "bankofbaroda.in",
    "canarabank.com",
    "unionbankofindia.co.in",
    "indianbank.in",
    "centralbankofindia.co.in",
    # India — fintech & brokers
    "paytm.com",
    "phonepe.com",
    "gpay.com",
    "googlepay.com",
    "bharatpe.com",
    "mobikwik.com",
    "freecharge.in",
    "razorpay.com",
    "cashfree.com",
    "payu.in",
    "billdesk.com",
    "ccavenue.com",
    "groww.in",
    "zerodha.com",
    "upstox.com",
    "angelone.in",
    "5paisa.com",
    "icicidirect.com",
    "hdfcsec.com",
    "kotaksecurities.com",
    "motilaloswal.com",
    "kuvera.in",
    "smallcase.com",
    "etmoney.com",
    "kuvera.in",
    "cred.club",
    "jupiter.money",
    "fi.money",
    "navi.com",
    "bajajfinserv.in",
    "policybazaar.com",
    # US / global
    "chase.com",
    "bankofamerica.com",
    "wellsfargo.com",
    "citi.com",
    "citibank.com",
    "capitalone.com",
    "americanexpress.com",
    "discover.com",
    "usbank.com",
    "pnc.com",
    "tdbank.com",
    "ally.com",
    "sofi.com",
    "robinhood.com",
    "fidelity.com",
    "schwab.com",
    "vanguard.com",
    "etrade.com",
    "interactivebrokers.com",
    "plaid.com",
    "paypal.com",
    "stripe.com",
    "square.com",
    "block.xyz",
    "wise.com",
    "revolut.com",
    "monzo.com",
    "starlingbank.com",
    "n26.com",
    "klarna.com",
    "affirm.com",
    "afterpay.com",
    "coinbase.com",
    "binance.com",
    "kraken.com",
    "gemini.com",
    "venmo.com",
    "cash.app",
    "zellepay.com",
    # EU
    "deutsche-bank.de",
    "ing.com",
    "bnpparibas.com",
    "societegenerale.com",
    "barclays.com",
    "hsbc.com",
    "lloydsbank.com",
    "natwest.com",
    "santander.com",
    "bbva.com",
]

# ---------------------------------------------------------------------------
# Shopping & e-commerce
# ---------------------------------------------------------------------------

SHOPPING_DOMAINS = [
    # India
    "amazon.in",
    "flipkart.com",
    "myntra.com",
    "ajio.com",
    "tatacliq.com",
    "nykaa.com",
    "meesho.com",
    "snapdeal.com",
    "shopclues.com",
    "bigbasket.com",
    "blinkit.com",
    "zepto.co",
    "dunzo.com",
    "jiomart.com",
    "reliancedigital.in",
    "croma.com",
    "pepperfry.com",
    "urbanladder.com",
    "lenskart.com",
    "firstcry.com",
    "purplle.com",
    "boat-lifestyle.com",
    "oneplus.in",
    "mi.com",
    "samsung.com",
    # US / global
    "amazon.com",
    "amazon.co.uk",
    "amazon.de",
    "amazon.fr",
    "amazon.ca",
    "amazon.com.au",
    "ebay.com",
    "etsy.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "costco.com",
    "homedepot.com",
    "lowes.com",
    "wayfair.com",
    "chewy.com",
    "newegg.com",
    "aliexpress.com",
    "alibaba.com",
    "shein.com",
    "temu.com",
    "wish.com",
    "shopify.com",
    "shop.app",
    # EU
    "zalando.com",
    "asos.com",
    "otto.de",
    "bol.com",
    "cdiscount.com",
    "fnac.com",
    "ikea.com",
    "decathlon.com",
    "hm.com",
    "zara.com",
    "uniqlo.com",
    "nike.com",
    "adidas.com",
]

FOOD_DELIVERY_DOMAINS = [
    "swiggy.in",
    "zomato.com",
    "ubereats.com",
    "doordash.com",
    "grubhub.com",
    "postmates.com",
    "deliveroo.com",
    "just-eat.com",
    "foodpanda.com",
    "dominos.com",
    "dominos.in",
    "pizzahut.com",
    "mcdonalds.com",
    "kfc.com",
    "burgerking.com",
    "starbucks.com",
    "dunkindonuts.com",
    "instacart.com",
    "zepto.co",
    "blinkit.com",
    "dunzo.com",
    "eatfit.in",
    "freshmenu.com",
]

# ---------------------------------------------------------------------------
# Travel & mobility
# ---------------------------------------------------------------------------

TRAVEL_DOMAINS = [
    # India
    "irctc.co.in",
    "makemytrip.com",
    "goibibo.com",
    "yatra.com",
    "cleartrip.com",
    "redbus.in",
    "indigo.in",
    "airindia.in",
    "spicejet.com",
    "vistara.com",
    "goindigo.in",
    "ola.com",
    "olacabs.com",
    "rapido.bike",
    # Global
    "airbnb.com",
    "booking.com",
    "expedia.com",
    "hotels.com",
    "agoda.com",
    "kayak.com",
    "skyscanner.com",
    "tripadvisor.com",
    "priceline.com",
    "orbitz.com",
    "travelocity.com",
    "delta.com",
    "united.com",
    "aa.com",
    "southwest.com",
    "jetblue.com",
    "britishairways.com",
    "lufthansa.com",
    "emirates.com",
    "qatarairways.com",
    "singaporeair.com",
    "ryanair.com",
    "easyjet.com",
    "uber.com",
    "lyft.com",
    "lyftmail.com",
    "grab.com",
    "bolt.eu",
    "blablacar.com",
    "rome2rio.com",
    "omio.com",
    "trainline.com",
    "flixbus.com",
    "marriott.com",
    "hilton.com",
    "ihg.com",
    "hyatt.com",
    "accor.com",
    "hostelworld.com",
    "couchsurfing.com",
]

# ---------------------------------------------------------------------------
# Social media & communities
# ---------------------------------------------------------------------------

SOCIAL_DOMAINS = [
    "linkedin.com",
    "linkedinmail.com",
    "facebookmail.com",
    "facebook.com",
    "meta.com",
    "instagram.com",
    "twitter.com",
    "x.com",
    "snapchat.com",
    "tiktok.com",
    "pinterest.com",
    "reddit.com",
    "redditmail.com",
    "discord.com",
    "discordapp.com",
    "telegram.org",
    "t.me",
    "whatsapp.com",
    "signal.org",
    "threads.net",
    "mastodon.social",
    "bsky.app",
    "quora.com",
    "medium.com",
    "tumblr.com",
    "nextdoor.com",
    "meetup.com",
    "clubhouse.com",
    "be-real.com",
    "bereal.com",
]

# ---------------------------------------------------------------------------
# Entertainment & streaming
# ---------------------------------------------------------------------------

ENTERTAINMENT_DOMAINS = [
    "netflix.com",
    "spotify.com",
    "youtube.com",
    "google.com",
    "primevideo.com",
    "amazonprime.com",
    "hotstar.com",
    "disneyplus.com",
    "disney.com",
    "hulu.com",
    "hbo.com",
    "max.com",
    "peacocktv.com",
    "paramountplus.com",
    "apple.com",
    "tv.apple.com",
    "music.apple.com",
    "crunchyroll.com",
    "sonyliv.com",
    "zee5.com",
    "voot.com",
    "jiocinema.com",
    "mxplayer.in",
    "altbalaji.com",
    "gaana.com",
    "wynk.in",
    "jiosaavn.com",
    "soundcloud.com",
    "deezer.com",
    "tidal.com",
    "pandora.com",
    "audible.com",
    "kindle.com",
    "steam.com",
    "steampowered.com",
    "epicgames.com",
    "playstation.com",
    "xbox.com",
    "nintendo.com",
    "twitch.tv",
    "roblox.com",
    "minecraft.net",
]

# ---------------------------------------------------------------------------
# Newsletters & media
# ---------------------------------------------------------------------------

NEWSLETTER_DOMAINS = [
    "substack.com",
    "medium.com",
    "beehiiv.com",
    "tldrnewsletter.com",
    "deeplearning.ai",
    "joinsuperhuman.ai",
    "codepen.io",
    "ghost.io",
    "mailchi.mp",
    "mailchimp.com",
    "convertkit.com",
    "buttondown.email",
    "revue.co",
    "the-ken.com",
    "morningbrew.com",
    "thehustle.co",
    "axios.com",
    "nytimes.com",
    "washingtonpost.com",
    "wsj.com",
    "ft.com",
    "economist.com",
    "bloomberg.com",
    "reuters.com",
    "theguardian.com",
    "bbc.com",
    "bbc.co.uk",
    "cnn.com",
    "forbes.com",
    "techcrunch.com",
    "theverge.com",
    "arstechnica.com",
    "wired.com",
    "hindustantimes.com",
    "timesofindia.com",
    "indianexpress.com",
    "thehindu.com",
    "livemint.com",
    "business-standard.com",
    "moneycontrol.com",
    "economictimes.com",
    "financialexpress.com",
    "scroll.in",
    "thewire.in",
    "quartz.com",
    "stratechery.com",
    "lennysnewsletter.com",
    "producthunt.com",
]

# ---------------------------------------------------------------------------
# Jobs & recruiting platforms
# ---------------------------------------------------------------------------

JOB_DOMAINS = [
    "linkedin.com",
    "linkedinmail.com",
    "naukri.com",
    "naukri.mail",
    "indeed.com",
    "indeedemail.com",
    "unstop.news",
    "unstop.com",
    "shine.com",
    "monster.com",
    "wellfound.com",
    "angel.co",
    "greenhouse.io",
    "lever.co",
    "smartrecruiters.com",
    "ashbyhq.com",
    "workday.com",
    "myworkday.com",
    "icims.com",
    "jobvite.com",
    "bamboohr.com",
    "recruitee.com",
    "teamtailor.com",
    "hirevue.com",
    "hackerrank.com",
    "codesignal.com",
    "codility.com",
    "leetcode.com",
    "instahyre.com",
    "hirist.com",
    "foundit.in",
    "timesjobs.com",
    "glassdoor.com",
    "ziprecruiter.com",
    "dice.com",
    "hired.com",
    "otta.com",
    "remoteok.com",
    "weworkremotely.com",
    "flexjobs.com",
    "upwork.com",
    "fiverr.com",
    "toptal.com",
    "haystack.cv",
    "careers.amazon.com",
    "amazon.jobs",
    "careers.google.com",
    "careers.microsoft.com",
]

JOB_APPLICATION_SENDER_SUFFIXES = [
    "@careers.amazon.com",
    "@amazon.jobs",
    "@greenhouse.io",
    "@lever.co",
    "@myworkday.com",
    "@smartrecruiters.com",
    "@ashbyhq.com",
]

# ---------------------------------------------------------------------------
# Education
# ---------------------------------------------------------------------------

EDUCATION_DOMAINS = [
    "coursera.org",
    "udemy.com",
    "edx.org",
    "udacity.com",
    "skillshare.com",
    "pluralsight.com",
    "linkedin.com",
    "khanacademy.org",
    "codecademy.com",
    "freecodecamp.org",
    "datacamp.com",
    "brilliant.org",
    "masterclass.com",
    "duolingo.com",
    "byjus.com",
    "unacademy.com",
    "vedantu.com",
    "toppr.com",
    "physicswallah.live",
    "upgrad.com",
    "simplilearn.com",
    "greatlearning.in",
    "scaler.com",
    "interviewbit.com",
    "leetcode.com",
    "hackerrank.com",
    "kaggle.com",
    "mit.edu",
    "stanford.edu",
    "harvard.edu",
    "berkeley.edu",
    "cmu.edu",
    "iit.ac.in",
    "iitb.ac.in",
    "iitd.ac.in",
    "bits-pilani.ac.in",
    "nptel.ac.in",
    ".edu",
    ".ac.in",
    ".ac.uk",
    ".edu.au",
]

# ---------------------------------------------------------------------------
# Work & productivity (SaaS)
# ---------------------------------------------------------------------------

WORK_DOMAINS = [
    "slack.com",
    "slack-mail.com",
    "jira.com",
    "atlassian.com",
    "atlassian.net",
    "asana.com",
    "notion.so",
    "linear.app",
    "clickup.com",
    "trello.com",
    "monday.com",
    "basecamp.com",
    "airtable.com",
    "figma.com",
    "miro.com",
    "mural.co",
    "loom.com",
    "zoom.us",
    "zoom.com",
    "meet.google.com",
    "calendar.google.com",
    "microsoft.com",
    "office.com",
    "teams.microsoft.com",
    "outlook.com",
    "salesforce.com",
    "hubspot.com",
    "zendesk.com",
    "freshdesk.com",
    "intercom.io",
    "helpscout.com",
    "front.com",
    "superhuman.com",
    "hey.com",
    "proton.me",
    "fastmail.com",
    "todoist.com",
    "ticktick.com",
    "evernote.com",
    "obsidian.md",
    "roamresearch.com",
    "coda.io",
    "confluence",
    "smartsheet.com",
    "wrike.com",
    "teamgantt.com",
    "height.app",
    "shortcut.com",
    "pagerduty.com",
    "opsgenie.com",
    "statuspage.io",
]

# ---------------------------------------------------------------------------
# Bills & utilities
# ---------------------------------------------------------------------------

BILL_DOMAINS = [
    "airtel.in",
    "jio.com",
    "vodafone.com",
    "vi.in",
    "bsnl.in",
    "verizon.com",
    "att.com",
    "t-mobile.com",
    "comcast.com",
    "xfinity.com",
    "spectrum.com",
    "pgande.com",
    "pge.com",
    "sce.com",
    "conedison.com",
    "nationalgrid.com",
    "duke-energy.com",
    "adani.com",
    "adanielectricity.com",
    "torrentpower.com",
    "bescom.org",
    "mseb.com",
    "mahadiscom.in",
    "tangedco.org",
    "bsesdelhi.com",
    "actcorp.in",
    "hathway.com",
    "excitel.com",
    "tataplay.com",
    "dish.com",
    "directv.com",
    "dishnetwork.com",
]

# ---------------------------------------------------------------------------
# Health & wellness
# ---------------------------------------------------------------------------

HEALTH_DOMAINS = [
    "practo.com",
    "apollo247.com",
    "apollopharmacy.in",
    "1mg.com",
    "netmeds.com",
    "pharmeasy.in",
    "medlife.com",
    "cvs.com",
    "walgreens.com",
    "riteaid.com",
    "labcorp.com",
    "questdiagnostics.com",
    "healthians.com",
    "thyrocare.com",
    "drlalpathlabs.com",
    "metropolisindia.com",
    "maxhealthcare.in",
    "fortishealthcare.com",
    "manipalhospitals.com",
    "cult.fit",
    "healthifyme.com",
    "fitbit.com",
    "garmin.com",
    "whoop.com",
    "ouraring.com",
    "headspace.com",
    "calm.com",
    "betterhelp.com",
    "teladoc.com",
    "mdlive.com",
    "zocdoc.com",
    "myfitnesspal.com",
]

# ---------------------------------------------------------------------------
# Government & civic (patterns)
# ---------------------------------------------------------------------------

GOVERNMENT_DOMAINS = [
    ".gov",
    ".gov.in",
    ".gov.uk",
    ".gov.au",
    ".gov.ca",
    "irs.gov",
    "ssa.gov",
    "uscis.gov",
    "dmv.",
    "uidai.gov.in",
    "passportindia.gov.in",
    "incometax.gov.in",
    "epfindia.gov.in",
    "nic.in",
    "digitalindia.gov.in",
    "mygov.in",
    "umang.gov.in",
    "digilocker.gov.in",
    "parivahan.gov.in",
    "gst.gov.in",
    "eaadhaar.uidai.gov.in",
    "onlinesbi.sbi",
    "india.gov.in",
    "europa.eu",
    "gov.uk",
    "service.gov.uk",
]

# ---------------------------------------------------------------------------
# Developer, cloud & DevOps
# ---------------------------------------------------------------------------

DEV_DOMAINS = [
    "github.com",
    "gitlab.com",
    "bitbucket.org",
    "stackoverflow.com",
    "stackoverflow.email",
    "docker.com",
    "hub.docker.com",
    "aws.amazon.com",
    "amazonaws.com",
    "cloud.google.com",
    "googlecloud.com",
    "azure.microsoft.com",
    "microsoftazure.com",
    "digitalocean.com",
    "vercel.com",
    "netlify.com",
    "render.com",
    "railway.app",
    "fly.io",
    "heroku.com",
    "supabase.com",
    "firebase.google.com",
    "mongodb.com",
    "planetscale.com",
    "neon.tech",
    "turso.tech",
    "cloudflare.com",
    "fastly.com",
    "akamai.com",
    "sentry.io",
    "datadoghq.com",
    "newrelic.com",
    "grafana.com",
    "prometheus.io",
    "pagerduty.com",
    "opsgenie.com",
    "circleci.com",
    "travis-ci.com",
    "jenkins.io",
    "hashicorp.com",
    "terraform.io",
    "pulumi.com",
    "npmjs.com",
    "pypi.org",
    "packagist.org",
    "rubygems.org",
    "crates.io",
    "nuget.org",
    "huggingface.co",
    "replicate.com",
    "openai.com",
    "anthropic.com",
    "cursor.com",
    "jetbrains.com",
    "intellij.com",
    "postman.com",
    "insomnia.rest",
    "swagger.io",
    "sonarsource.com",
    "snyk.io",
    "dependabot.com",
    "renovatebot.com",
    "codecov.io",
    "coveralls.io",
    "semgrep.dev",
    "launchdarkly.com",
    "amplitude.com",
    "mixpanel.com",
    "segment.com",
    "rudderstack.com",
]

# ---------------------------------------------------------------------------
# Promotions (marketing senders often overlap shopping)
# ---------------------------------------------------------------------------

PROMOTION_SENDER_HINTS = [
    "marketing",
    "promo",
    "offers",
    "deals",
    "newsletter",
    "noreply",
    "no-reply",
    "notifications",
]
